-- 1. 현재 시간을 조회한다.
SELECT SYSDATE
  FROM DUAL    -- DUAL --> DUMMY TABLE
;

-- 2. 현재 시간을 "연-월-일" 포멧으로 조회한다.
--SELECT TO_CHAR(날짜타입, 포맷)
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
  FROM DUAL
;
-- 3. 한 시간 전 시간을 "시:분:초" 포멧으로 조회한다.
SELECT TO_CHAR(SYSDATE - 1/24, 'HH:MI:SS')
	 , TO_CHAR(SYSDATE + 5/24, 'HH24:MI:SS')
  FROM DUAL
;
-- 4. EMPLOYEES 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMETN_ID
  FROM EMPLOYEES
;  
-- 5. DEPARTMENTS 테이블의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID
	 , DEPARTMENT_NAME
	 , MANAGER_ID
	 , LOCATION_ID
  FROM DEPARTMENTS
;
-- 6. JOBS 테이블의 모든 정보를 조회한다.
SELECT JOB_ID
	  ,JOB_TITLE
	  ,MIN_SALARY
	  ,MAX_SALARY
  FROM JOBS
;
-- 7. LOCATIONS 테이블의 모든 정보를 조회한다.
SELECT LOCATION_ID
	  ,STREET_ADDRESS
	  ,POSTAL_CODE
	  ,CITY
	  ,STATE_PROVINCE
	  ,COUNTRY_ID
  FROM LOCATIONS
;
-- 8. COUNTRIES 테이블의 모든 정보를 조회한다.
SELECT COUNTRY_ID
	  ,COUNTRY_NAME
	  ,REGION_ID
  FROM COUNTRIES
;
-- 9. REGIONS 테이블의 모든 정보를 조회한다.
SELECT REGION_ID
	  ,REGION_NAME
  FROM REGIONS
;
-- 10. JOB_HISTORY 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,START_DATE
	  ,END_DATE
	  ,JOB_ID
	  ,DEPARTMENT_ID
  FROM JOB_HISTORY
;
-- 11. 상사사원번호를 중복없이 조회한다.
SELECT DISTINCT MANAGER_ID
  FROM EMPLOYEES
;

-- 12. 90번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT *
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 90
  ;

-- 13. 90번, 100번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (90,100)
;

-- 14. 100번 상사의 직속 부하직원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE MANAGER_ID = 100
;

-- 15. 111번 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 111
;

-- 16. 직무 아이디가 AD_VP 인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE JOB_ID = 'AD_VP'
;

-- 17. 급여가 7000 이상인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE SALARY >= 7000
;

-- 18. 직무 아이디가 'PU_CLERK'인 사원 중 급여가 3000 이상인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE JOB_ID = 'PU_CLERK'
   AND SALARY >= 3000
;

-- 19. 급여가 2500, 3500, 7000 이 아니며 직업이 SA_REP 이나 ST_CLERK 인 사원들의 
--     모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE SALARY NOT IN (2500, 3500, 7000)
   AND JOB_ID IN ('SA_REP', 'ST_CLERK')
;

-- 20. 커미션을 안받는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL
;

-- 21. 커미션을 받는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
;

-- 22. 이름의 첫 글자가 'D' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'D%'
;

-- 23. 성의 마지막 글자가 'a' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE LAST_NAME LIKE '%a'
;

-- 24. 전화번호에 '.124.'이 포함된 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '%.124.%'
;

-- 25. 이름이 4글자인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '____'
;

-- 26. 이름이나 성에 'A' 혹은 'a' 가 포함된 사원의 모든 정보를 조회한다.
SELECT  
(SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
	  ,LOWER(FIRST_NAME || LAST_NAME) AS NAME
  FROM EMPLOYEES)
  WHERE NAME LIKE '%a%'
/*  
 WHERE FIRST_NAME LIKE '%A%'
    OR FIRST_NAME LIKE '%a%'
    OR LAST_NAME LIKE '%A%'
    OR LAST_NAME LIKE '%a%' */
  
;

-- 27. 국가명이 6자리인 국가의 모든 정보를 조회한다.
SELECT COUNTRY_ID
	 , COUNTRY_NAME
	 , REGION_ID
  FROM COUNTRIES
 WHERE COUNTRY_NAME LIKE ('______')
;

-- 28. '20230222' 문자 데이터를 날짜로 변환해 조회한다.(DUAL)
SELECT '20230222'
	  ,TO_DATE('20230222', 'YYYY-MM-DD')
  FROM DUAL
;

-- 29. '20230222' 문자 데이터를 'YYYY-MM' 으로 변환해 조회한다.(DUAL)
SELECT TO_DATE('20230222', 'YYYY-MM-DD')
	  ,TO_CHAR(TO_DATE('20230222', 'YYYY-MM-DD'), 'YYYY-MM')
  FROM DUAL
;

-- 30. '20230222130140' 문자 데이터를 'YYYY-MM-DD HH24:MI:SS' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(TO_DATE('20230222130140', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS')
  FROM DUAL
;

-- 31. '20230222' 날짜의 열흘 후의 날짜를 'YYYY-MM-DD' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(TO_DATE('20230222', 'YYYY-MM-DD') + 10, 'YYYY-MM-DD')
  FROM DUAL
;

-- 32. 직원의 입사일자를 '연-월-일' 형태로 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY-MM-DD')
  FROM EMPLOYEES
;
-- 33. 2005년 09월에 입사한 사원들의 모든 정보를 조회한다.
SELECT *
  FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN TO_DATE('2005-09-01', 'YYYY-MM-DD') AND TO_DATE('2005-10-01', 'YYYY-MM-DD') - 1
/*WHERE HIRE_DATE >= TO_DATE('2005-09-01', 'YYYY-MM-DD')
    AND HIRE_DATE <= TO_DATE('2005-10-01', 'YYYY-MM-DD') - 1*/
;

-- 34. 현재 시간으로부터 20년 전 보다 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT *
  FROM EMPLOYEES
 WHERE HIRE_DATE < ADD_MONTHS(SYSDATE, -20 * 12)
 ORDER BY HIRE_DATE DESC
;

-- 35. 사원들의 정보 중 입사연도, 이름, 성만 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY')
	  ,FIRST_NAME
	  ,LAST_NAME
  FROM EMPLOYEES
;
-- 36. 사원들의 정보 중 입사연도, 입사월, 이름, 성만 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY')
	  ,TO_CHAR(HIRE_DATE, 'MM')
	  ,FIRST_NAME
	  ,LAST_NAME
  FROM EMPLOYEES
;
-- 37. MOD 함수를 통해 사원번호가 홀수면 남자, 짝수면 여자 로 구분해 조회한다. MOD(값, 나눌값)
-- 38. 사원 모든 정보 중 이메일만 모두 소문자로 변경하여 조회한다.
-- 39. 사원의 급여를 TRUNC(소수점 버림) 함수를 사용해 100 단위는 버린채 다음과 같이 조회한다. 
--     예> 3700 -> 3000, 12700 -> 12000
-- 40. 100단위를 버린 사원의 급여 별 사원의 수를 조회한다.
-- 41. 모든 사원들의 이름을 10자리로 맞추어 조회한다.
-- 42. 사원의 이름과 성을 이용해 EMAIL과 같은 값으로 만들어 조회한다.
-- 43. 모든 사원들의 이름을 10자리로 변환해 조회한다. 예> 이름 => "        이름"
-- 44. 모든 사원들의 성을 10자리로 변환해 조회한다. 예> 성 => "성         "
-- 45. 모든 사원들의 모든 정보를 조회한다. 
--     단, 커미션을 받는 사원은 "커미션여부" 컬럼에 "Y"를, 아닌 경우 "N"으로 조회한다.
-- 46. 사원의 모든 정보를 조회한다. 
--     사원의 급여가 5000 이하이면 "사원", 
--                7000 이하이면 "대리", 
--                9000 이하이면 "과장", 
--                그 외에는 "임원" 으로 조회한다.
-- 47. 모든 사원들의 모든 정보를 급여 오름차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY SALARY ASC
;

-- 48. 모든 사원들의 모든 정보를 이름 내림차순 정렬하여 조회한다.
SELECT *
  FROM EMPLOYEES
 ORDER BY FIRST_NAME DESC
;

-- 49. 모든 사원들의 모든 정보를 직무 오름차순, 급여 내림차순으로 조회한다.
SELECT *
  FROM EMPLOYEES
 ORDER BY JOB_ID ASC
      ,SALARY DESC 
;
-- 50. 가장 늦게 입사한 사원의 모든 정보를 조회한다.
SELECT *
  FROM EMPLOYEES 
 WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE)
  					  FROM EMPLOYEES )
;

SELECT MIN(HIRE_DATE)
  FROM EMPLOYEES 
; 
-- 51. 가장 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT *
  FROM EMPLOYEES 
 WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE)
  					  FROM EMPLOYEES )
;
-- 52. 사내의 최고급여과 최저급여의 차이를 조회한다.
SELECT MAX(SALARY) - MIN(SALARY)
  FROM EMPLOYEES
;

-- 53. 102번 직원의 직속 부하직원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 102
;

-- 54. 113번 직원의 직속 부하직원의 수를 조회한다.
SELECT COUNT(MANAGER_ID)
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 113
;

-- 55. 'SA_REP' 직무인 직원 중 가장 높은 급여과 가장 낮은 급여를 조회한다.
SELECT MAX(SALARY)
     , MIN(SALARY)
  FROM EMPLOYEES
 WHERE JOB_ID = 'SA_REP'
;

-- 56. 부서아이디별 평균 급여를 조회한다.
SELECT DEPARTMENT_ID
     , AVG(SALARY)
  FROM EMPLOYEES 
 GROUP BY DEPARTMENT_ID 
;

-- 57. 직무아이디별 평균 급여, 최고급여, 최저급여를 조회한다.
SELECT JOB_ID
	 , AVG(SALARY)
	 , MAX(SALARY)
	 , MIN(SALARY)
  FROM EMPLOYEES
 GROUP BY JOB_ID
;

-- 58. 직무아이디별 사원의 수를 조회한다.
SELECT JOB_ID
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES 
 GROUP BY JOB_ID
;
-- 59. 상사아이디별 부하직원의 수를 조회한다. 단, 부하직원이 2명 이하인 경우는 제외한다.
SELECT MANAGER_ID 
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY MANAGER_ID
HAVING COUNT(EMPLOYEE_ID) > 2
;
-- 60. 부서번호별 현재 시간으로부터 15년 전 보다 일찍 입사한 사원의 수를 조회한다.
SELECT DEPARTMENT_ID
     , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 WHERE HIRE_DATE < ADD_MONTHS(SYSDATE, -15 * 12)
 GROUP BY DEPARTMENT_ID
;

-- 61. 커미션을 안받는 사원이 근무하는 도시를 조회한다.
SELECT DISTINCT DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL
;

SELECT DISTINCT LOCATION_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID 
  						   FROM EMPLOYEES
 						  WHERE COMMISSION_PCT IS NULL)
;

SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID
  						 FROM DEPARTMENTS
 					    WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID 
  						   						  FROM EMPLOYEES
 						  						 WHERE COMMISSION_PCT IS NULL))			
;
-- 62. 회사 전체의 평균 급여보다 많이 받는 사원들 중 
--     이름에 'u' 가 포함된 사원과 동일한 부서에서 근무중인 사원들의 모든 정보를 조회한다.
-- 1. 특정할 수 없는 것?
-- 평균 급여
SELECT AVG(SALARY)
  FROM EMPLOYEES
;
-- 이름에 'u' 가 포함된 사원의 부서 번호(60,100,30,50,80,40) -- 중복제거
SELECT DISTINCT DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%u%'
;
-- 2. 비교
-- 평균급여와 사원들의 급여 
-- 이름에 U가 포함된 사원의 부서 번호와 사원들이 근무중빈 부서의 번호

SELECT *
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
  				   FROM EMPLOYEES)
   AND DEPARTMENT_ID IN (SELECT DISTINCT EMPLOYEE_ID
  						   FROM EMPLOYEES
 						  WHERE FIRST_NAME LIKE '%u%'))
;
-- 63. 이름이 'Renske' 인 사원의 급여와 같은 급여를 받는 사원의 모든 정보를 조회한다. 
--     단, 'Renske' 사원은 조회에서 제외한다.
-- 1. 특정할 수 없는 것?  RENSKE 사원의 급여 -> 3600
SELECT SALARY
  FROM EMPLOYEES 
 WHERE FIRST_NAME = 'Renske' 
;
-- 2. 사원들의 급여와 비교
SELECT *
  FROM EMPLOYEES
 WHERE SALARY = (SELECT SALARY
  				   FROM EMPLOYEES 
 				  WHERE FIRST_NAME = 'Renske')
   AND FIRST_NAME != 'Renske' 
;

-- 64. 평균 급여보다 많이 받는 사원들의 사원번호, 이름, 성, 급여를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
  				   FROM EMPLOYEES)
;
-- 65. 평균 급여보다 적게 받는 사원들의 사원번호, 급여, 부서번호를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY < (SELECT AVG(SALARY)
  				   FROM EMPLOYEES)
;
-- 66. 가장 많은 급여를 받는 사원의 사원번호, 이름, 급여를 조회한다.
SELECT MAX(SALARY)
  FROM EMPLOYEES
;

SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY = (SELECT MAX(SALARY)
 				   FROM EMPLOYEES)
;
-- 67. 자신의 상사보다 더 많은 급여를 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.SALARY > (SELECT E_MAN.SALARY 
 				     FROM EMPLOYEES E_MAN
 				    WHERE E_MAN.EMPLOYEE_ID = E.MANAGER_ID)
;
-- 68. 자신의 상사보다 더 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.HIRE_DATE < (SELECT E_MAN.HIRE_DATE 
 				        FROM EMPLOYEES E_MAN
 				       WHERE E_MAN.EMPLOYEE_ID = E.MANAGER_ID)
;

-- 69. 가장 많은 커미션을 받는 사원의 모든 정보를 조회한다.
-- 1. 특정할 수 없는 것?  최대 커미션 비율 -> 0.4
SELECT MAX(COMMISSION_PCT)
  FROM EMPLOYEES 
;
-- 2. 무엇과 비교할 거인가? 최대 커미션 비율과 사원들의 커미션 비율

SELECT *
  FROM EMPLOYEES
 WHERE COMMISSION_PCT = (SELECT MAX(COMMISSION_PCT)
  						   FROM EMPLOYEES)
;
-- 70. 가장 적은 커미션을 받는 사원의 급여와 커미션을 조회한다.
SELECT *
  FROM EMPLOYEES
 WHERE COMMISSION_PCT = (SELECT MIN(COMMISSION_PCT)
  						   FROM EMPLOYEES)
;
-- 71. 사원이 속한 부서의 평균급여보다 적게 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.SALARY < (SELECT AVG(SALARY)
 					 FROM EMPLOYEES E_MAN
 					WHERE E.DEPARTMENT_ID = E_MAN.DEPARTMENT_ID)
;
  
-- 72. 50번 부서의 부서장의 이름, 성, 급여를 조회한다.
-- 1. 50번 부서의 부서장 사원 번호 -->121
SELECT MANAGER_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID = 50 
;
-- 2. 무엇과 비교해야 하는가? 50번 부서의 부서장 사원번호화 사원의 사원 번호
SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 121
;

 SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = (SELECT MANAGER_ID
 					   FROM DEPARTMENTS
 					  WHERE DEPARTMENT_ID = 50)
; 
-- 73. 사원이 없는 부서명을 조회한다.
--1. 특정할 수 없는 것?  사원들이 근무중인 부서의 번호 (중복 제거) / 사원 - 부서 = 답 
SELECT DISTINCT DEPARTMENT_ID 
  FROM EMPLOYEES
;
--2. 사원들이 근무중인 부서의 번호와 부서 정보의 부서번호 (근무하는 사원이 존재하지 않는)
SELECT DEPARTMENT_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID NOT IN (SELECT DISTINCT DEPARTMENT_ID 
  							   FROM EMPLOYEES
  							  WHERE DEPARTMENT_ID IS NOT NULL)
;
-- 74. 직무가 변경된 사원의 모든 정보를 조회한다.
--1. 직무가 변경된 사원들의 사원 번호 -> 중복제거
SELECT DISTINCT EMPLOYEE_ID  
  FROM JOB_HISTORY
;
--사원들이 번호와 직무가 변경된 사원들의 번호 (존재하는)
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (SELECT DISTINCT EMPLOYEE_ID 
  						 FROM JOB_HISTORY)
;
-- 75. 직무가 변경된적 없는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (SELECT DISTINCT EMPLOYEE_ID 
  						 	 FROM JOB_HISTORY)
;
-- 76. 직무가 가장 많이 변경된 부서의 이름을 조회한다.
SELECT DEPARTMENT_NAME
  FROM (SELECT DEPARTMENT_NAME
  			 , ROWNUM
 		  FROM DEPARTMENTS D
 		 INNER JOIN JOB_HISTORY JH
 		    ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID)
 WHERE ROWNUM = 1
;

SELECT DEPARTMENT_NAME
  	 , ROWNUM
  FROM DEPARTMENTS D
 INNER JOIN JOB_HISTORY JH
 	ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE 
;

SELECT DEPARTMENT_ID
     , COUNT(EMPLOYEE_ID)
--   , COUNT(EMPLOYEE_ID) 별로 순위를 구한다.
     , RANK() OVER(ORDER BY COUNT(EMPLOYEE_ID)DESC)
  FROM JOB_HISTORY   
 GROUP BY DEPARTMENT_ID 
;

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
						  FROM (SELECT DEPARTMENT_ID
									 , RANK() OVER( ORDER BY EMP_CNT DESC ) AS RANK
								  FROM (SELECT DEPARTMENT_ID
											 , COUNT(EMPLOYEE_ID) AS EMP_CNT
										  FROM JOB_HISTORY
										 GROUP BY DEPARTMENT_ID))
						 WHERE RANK = 1)
;
-- 77. 근무중인 사원이 없는 도시를 조회한다.
SELECT DISTINCT DEPARTMENT_ID
  FROM EMPLOYEES
;

SELECT DISTINCT LOCATION_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID
  						   FROM EMPLOYEES) 
;

SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID NOT IN(SELECT DISTINCT LOCATION_ID
  							FROM DEPARTMENTS
 						   WHERE DEPARTMENT_ID IN(SELECT DISTINCT DEPARTMENT_ID
  						       						FROM EMPLOYEES
  						  						   WHERE DEPARTMENT_ID IS NOT NULL))
;
-- 78. 급여가 7000 에서 12000 사이인 사원이 근무중인 도시를 조회한다.
SELECT DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE SALARY BETWEEN 7000 AND 12000
;

SELECT DISTINCT LOCATION_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
  						   FROM EMPLOYEES
 						  WHERE SALARY BETWEEN 7000 AND 12000)
;

SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID
 						 FROM DEPARTMENTS
						WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
  						 						  FROM EMPLOYEES
 										   	     WHERE SALARY BETWEEN 7000 AND 12000))
;
-- 79. 'Seattle' 에서 근무중인 사원의 직무명을 중복없이 조회한다.
SELECT LOCATION_ID
  FROM LOCATIONS
 WHERE CITY = 'Seattle'
;

SELECT DEPARTMENT_ID
  FROM DEPARTMENTS
 WHERE LOCATION_ID = (SELECT LOCATION_ID
  						FROM LOCATIONS
 					   WHERE CITY = 'Seattle')
;

SELECT DISTINCT JOB_ID
  FROM EMPLOYEES 
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
  						   FROM DEPARTMENTS
 						  WHERE LOCATION_ID = (SELECT LOCATION_ID
  												 FROM LOCATIONS
 					   							WHERE CITY = 'Seattle'))
;

SELECT JOB_TITLE
  FROM JOBS
 WHERE JOB_ID IN (SELECT DISTINCT JOB_ID
  					FROM EMPLOYEES 
 				   WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
  						  					 FROM DEPARTMENTS
 						  					WHERE LOCATION_ID = (SELECT LOCATION_ID
  																   FROM LOCATIONS
 					   											  WHERE CITY = 'Seattle')))
;
-- 80. 부서가 없는 국가명을 조회한다. -- IN에 들어가는 서브쿼리가 있을 때 중복제거
SELECT DISTINCT LOCATION_ID
  FROM DEPARTMENTS
;

SELECT DISTINCT COUNTRY_ID
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID
  				      FROM DEPARTMENTS)
;

SELECT COUNTRY_NAME
  FROM COUNTRIES
 WHERE COUNTRY_ID NOT IN (SELECT DISTINCT COUNTRY_ID
  							FROM LOCATIONS
 						   WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID
  				      							   FROM DEPARTMENTS
  				      							  WHERE LOCATION_ID IS NOT NULL))
;
-- 81. 'Europe' 에서 근무중인 사원들의 모든 정보를 조회한다.
SELECT REGION_ID
  FROM REGIONS
 WHERE REGION_NAME = 'Europe'
;

SELECT COUNTRY_ID
  FROM COUNTRIES
 WHERE REGION_ID = (SELECT REGION_ID
  					  FROM REGIONS
 					 WHERE REGION_NAME = 'Europe')
;

SELECT LOCATION_ID
  FROM LOCATIONS
 WHERE COUNTRY_ID IN (SELECT COUNTRY_ID
  						FROM COUNTRIES
 					   WHERE REGION_ID = (SELECT REGION_ID
  											FROM REGIONS
 										   WHERE REGION_NAME = 'Europe'))
;

SELECT DEPARTMENT_ID 
  FROM DEPARTMENTS
 WHERE LOCATION_ID IN (SELECT LOCATION_ID
  						 FROM LOCATIONS
 						WHERE COUNTRY_ID IN (SELECT COUNTRY_ID
  											   FROM COUNTRIES
 					   						  WHERE REGION_ID = (SELECT REGION_ID
  																   FROM REGIONS
 										   						  WHERE REGION_NAME = 'Europe')))
;

SELECT *
  FROM EMPLOYEES 
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
  						   FROM DEPARTMENTS
 						  WHERE LOCATION_ID IN (SELECT LOCATION_ID
  						 						  FROM LOCATIONS
 												 WHERE COUNTRY_ID IN (SELECT COUNTRY_ID
  											   							FROM COUNTRIES
 					   						  						   WHERE REGION_ID = (SELECT REGION_ID
  																   							FROM REGIONS
 										   						  						   WHERE REGION_NAME = 'Europe'))))
;
-- 82. 'Seattle' 에서 근무중인 사원의 이름, 성, 급여, 부서명 을 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 WHERE D.LOCATION_ID = (SELECT LOCATION_ID
 					   	   FROM LOCATIONS	
 						  WHERE CITY ='Seattle')
;    
-- 83. 'Seattle' 에서 근무하지 않는 모든 사원의 이름, 성, 급여, 부서명, 도시를 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY
	 , D.DEPARTMENT_NAME
	 , L.CITY
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 WHERE L.CITY != 'Seattle'
;
-- 84. 모든 사원들의 이름, 성, 급여, 부서명을 부서번호로 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_ID 
	 , E.FIRST_NAME 
     , E.LAST_NAME
     , E.SALARY
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 ORDER BY D.DEPARTMENT_ID DESC
;
-- 85. 2007년에 직무가 변경된 사원들의 현재 직무명, 부서명, 사원번호, 이름, 성을 조회한다.
SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME
	 , D.DEPARTMENT_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
 WHERE E.EMPLOYEE_ID  IN (SELECT EMPLOYEE_ID
 				  		   FROM JOB_HISTORY
 				  		  WHERE START_DATE >= TO_DATE('2007-01-01', 'YYYY-MM-DD'))
 				  		  	AND START_DATE <
;
-- 86. 부서장이 없는 부서명 중 첫 글자가 'C' 로 시작하는 부서명을 조회한다.

-- 87. 지역변호가 1000 ~ 1999 사이인 지역내 부서의 모든 정보를 조회한다.
SELECT LOCATION_ID
  FROM LOCATIONS
 WHERE LOCATION_ID BETWEEN 1000 AND 1999
;
SELECT *
  FROM DEPARTMENTS
 WHERE LOCATION_ID IN (SELECT LOCATION_ID
  						 FROM LOCATIONS
 					    WHERE LOCATION_ID BETWEEN 1000 AND 1999)		
;
-- 88. 국가 아이디가 'C'로 시작하는 국가의 지역을 모두 조회한다.
SELECT COUNTRY_ID
  FROM COUNTRIES
 WHERE COUNTRY_ID LIKE 'C%' 
;

SELECT *
  FROM LOCATIONS
 WHERE COUNTRY_ID IN (SELECT COUNTRY_ID
  						FROM COUNTRIES
 					   WHERE COUNTRY_ID LIKE 'C%')
;
-- 89. 109번 사원의 입사일 부터 1년 동안 입사한 사원의 모든 정보를 조회한다.
SELECT HIRE_DATE 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 109
;

SELECT *
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID BETWEEN (SELECT HIRE_DATE 
  							  FROM EMPLOYEES
 							 WHERE EMPLOYEE_ID = 109) AND ADD_MONTHS((SELECT HIRE_DATE 
  						 		     									FROM EMPLOYEES
 							           								   WHERE EMPLOYEE_ID = 109) , 12)
;
-- 90. 가장 먼저 입사한 사원의 입사일로부터 2년 동안 입사한사원의 모든 정보를 조회한다.

-- 91. 가장 늦게 입사한 사원의 입사일의 1년 전보다 일찍 입사한 사원의 모든 정보를 조회한다.

-- 92. 사원들이 근무하는 부서명, 이름, 성을 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , E.FIRST_NAME
	 , E.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
-- 93. 우편번호가 5자리인 도시에서 근무하는 사원명, 부서명, 도시명, 우편번호를 조회한다.
SELECT E.FIRST_NAME  
	 , D.DEPARTMENT_NAME 
     , L.CITY
     , L.POSTAL_CODE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
 WHERE L.POSTAL_CODE LIKE '_____'
;

SELECT E.FIRST_NAME
	 , L_D.DEPARTMENT_NAME
	 , L_D.CITY
	 , L_D.POSTAL_CODE
  FROM (SELECT L.CITY
             , L.POSTAL_CODE
             , D.LOCATION_ID
             , D.DEPARTMENT_NAME
          FROM (SELECT CITY
                     , POSTAL COE
                     , LOCATION_ID
                  FROM (SELECT CITY
                   	         , POSTAL_CODE
                   	         , LOCATION_ID
                   	         , LENGTH(POSTAL_CODE) AS POSTAL_LENGTH
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
;        

-- 94. 부서장이 있는 부서명 중 첫 글자가 'S' 로 시작하는 부서에서 근무중인 사원의 
--     이름과 직무명, 부서명을 조회한다.
SELECT E.FIRST_NAME
	 , J.JOB_TITLE
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
 WHERE D.DEPARTMENT_NAME IN (SELECT DEPARTMENT_NAME
 							   FROM DEPARTMENTS
 							  WHERE MANAGER_ID IN(SELECT MANAGER_ID
 							                        FROM DEPARTMENTS
 							                       WHERE DEPARTMENT_NAME LIKE 'S%'))
;
-- 95. 90, 60, 100번 부서에서 근무중인 사원의 이름, 성, 부서명을 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME
	 , D.DEPARTMENT_NAME
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 WHERE D.DEPARTMENT_ID IN ('90','60','100')
;
-- 96. 부서명이 5글자 미만인 부서에서 근무중인 사원의 이름, 부서명을 조회한다.
SELECT E.FIRST_NAME
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 WHERE D.DEPARTMENT_NAME NOT LIKE '_____%'
;
-- 97. 도시명에 띄어쓰기 " " 가 포함된 도시에서 근무중인 사원들의 부서명, 도시명, 사원명을 조회한다.
SELECT D.DEPARTMENT_NAME 
     , L.CITY
     , E.FIRST_NAME
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
 WHERE CITY LIKE '% %'
;
-- 98. 우편번호에 공백이 없는 도시에서 근무하는 사원의 이름, 부서명, 우편번호를 조회한다.
SELECT E.FIRST_NAME
     , D.DEPARTMENT_NAME
     , L.POSTAL_CODE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 WHERE POSTAL_CODE NOT LIKE '% %'
;
-- 99. "주"가 없는 도시에서 근무하는 사원의 이름, 도시를 조회한다.
SELECT E.FIRST_NAME 
     , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
 WHERE L.STATE_PROVINCE IS NULL 
;
-- 100. 사원들의 사원번호, 이름, 성, 상사의 사원번호, 상사의 이름, 상사의 성을 조회한다.
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME
	 , EM.EMPLOYEE_ID 
	 , EM.FIRST_NAME 
	 , EM.LAST_NAME 	 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES EM
    ON E.MANAGER_ID = EM.EMPLOYEE_ID 
; 
-- 101. 직무가 변경된 사원의 이름과 과거 직무명과 현재 직무명을 조회한다.
SELECT E.FIRST_NAME 
	 , J_PRESENT.JOB_TITLE AS PRESENT_JOB
	 , J_PAST.JOB_TITLE AS PAST_JOB
  FROM EMPLOYEES E
 INNER JOIN JOBS J_PRESENT
    ON E.JOB_ID = J_PRESENT.JOB_ID
 INNER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
 INNER JOIN JOBS J_PAST
    ON JH.JOB_ID = J_PAST.JOB_ID 
;    
    
-- 102. 가장 적은 급여를 받는 사원의 부서명, 이름, 성, 급여, 부서장사원번호를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.SALARY
	 , D.MANAGER_ID 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 WHERE E.JOB_ID IN (SELECT JOB_ID
 			         FROM JOBS
 			        WHERE E.SALARY = MIN_SALARY)
;
-- 103. 부서명별 사원의 수를 조회한다.
SELECT DEPARTMENT_NAME
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID  
 GROUP BY DEPARTMENT_NAME
 
;
-- 104. 대륙명별 사원의 수를 조회한다.
SELECT REGION_NAME
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID  
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON R.REGION_ID = C.REGION_ID 
 GROUP BY R.REGION_NAME
 ORDER BY R.REGION_NAME ASC
;
-- 105. 직무명별 최소급여를 조회한다.
SELECT J.JOB_TITLE 
	 , MIN(E.SALARY) 
  FROM JOBS J
 INNER JOIN EMPLOYEES E
    ON E.JOB_ID = J.JOB_ID
 GROUP BY J.JOB_TITLE
;
-- 106. 부서명별 최대급여를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , MAX(E.SALARY )
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
 GROUP BY D.DEPARTMENT_NAME
;

-- 107. 직무명별 평균급여를 평균급여순으로 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE
	 , AVG(E.SALARY) AS AVG_SLY
  FROM EMPLOYEES E
 INNER JOIN JOBS J 
    ON J.JOB_ID = E.JOB_ID 
 GROUP BY J.JOB_TITLE 
 ORDER BY AVG_SLY ASC
;

-- 108. 부서명별 평균급여를 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , AVG(E.SALARY) AS AVG_SLY
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY AVG_SLY DESC
;

-- 109. 부서명별 급여의 합을 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME
	 , SUM(E.SALARY) AS SUM_SLY
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY SUM_SLY DESC
;
-- 110. 직무명별 사원의 수를 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE
	 , COUNT(E.EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E 
 INNER JOIN JOBS J 
    ON J.JOB_ID = E.JOB_ID 
 GROUP BY J.JOB_TITLE
 ORDER BY EMP_CNT ASC
;
-- 111. 직무명, 부서명 별 사원 수, 평균급여를 조회한다.
SELECT J.JOB_TITLE
     , D.DEPARTMENT_NAME 
	 , COUNT(E.EMPLOYEE_ID)
	 , AVG(E.SALARY)
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
 GROUP BY JOB_TITLE
     , D.DEPARTMENT_NAME 
;
-- 112. 도시별 사원 수를 조회한다.
SELECT L.CITY
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
 GROUP BY L.CITY
;
-- 113. 국가별 사원 수, 최대급여, 최소급여를 조회한다.
SELECT C.COUNTRY_NAME
	 , COUNT(E.EMPLOYEE_ID) AS EMP_CNT
	 , MAX(E.SALARY) AS SLY_MAX
	 , MIN(E.SALARY) AS SLY_MIN
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID 
 GROUP BY C.COUNTRY_NAME
;
-- 114. 국가별로 급여가 5000 이상인 사원의 수를 조회한다.
SELECT C.COUNTRY_NAME
	 , COUNT(E.EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID 
 WHERE E.SALARY >= '5000'
 GROUP BY C.COUNTRY_NAME
;
-- 115. 부서명, 직무명 별 평균 급여를 조회한다.
SELECT D.DEPARTMENT_NAME 
 	 , J.JOB_TITLE
 	 , AVG(SALARY) 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
 GROUP BY D.DEPARTMENT_NAME 
 	 , J.JOB_TITLE 
;
-- 116. 도시명, 직무명 별 사원의 수를 조회한다.
SELECT L.CITY
	 , J.JOB_TITLE
	 , COUNT(EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
 GROUP BY L.CITY 
     , J.JOB_TITLE 
;
-- 117. 부서명, 직무명 별 평균 급여 중 가장 작은 평균급여를 받는 부서명, 직무명을 조회한다.
-- ROWNUM
SELECT DEPARTMENT_NAME
	 , JOB_TITLE
	 , SAL_AVG
	 , ROWNUM
  FROM (SELECT DEPARTMENT_NAME
		     , JOB_TITLE
		     , AVG(SALARY) AS SAL_AVG
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		 INNER JOIN JOBS J
		    ON J.JOB_ID = E.JOB_ID
		 GROUP BY D.DEPARTMENT_NAME
		     , J.JOB_TITLE
		 ORDER BY SAL_AVG ASC)
 WHERE ROWNUM = 1
;

SELECT DEPARTMENT_NAME
     , JOB_TITLE
     , AVG(SALARY) AS SAL_AVG
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
 GROUP BY D.DEPARTMENT_NAME
     , J.JOB_TITLE
 ORDER BY SAL_AVG ASC
;


-- RANK OVER
SELECT D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , AVG(SALARY) AS AVG_SALARY
	 , RANK() OVER( ORDER BY AVG(SALARY) ASC)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
 GROUP BY D.DEPARTMENT_NAME 
 	 , J.JOB_TITLE 

SELECT DEPARTMENT_NAME
	 , JOB_TITLE
  FROM (SELECT DEPARTMENT_NAME 
	 		 , JOB_TITLE
	 		 , AVG_SALARY
			 , RANK() OVER( ORDER BY AVG_SALARY ASC) AS RANK
  		  FROM (SELECT D.DEPARTMENT_NAME 
					 , J.JOB_TITLE 
	 				 , AVG(SALARY) AS AVG_SALARY
  		 		  FROM EMPLOYEES E
         		 INNER JOIN DEPARTMENTS D
           		    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
        		 INNER JOIN JOBS J
         		    ON E.JOB_ID = J.JOB_ID
       		     GROUP BY D.DEPARTMENT_NAME 
 	      		     , J.JOB_TITLE ))
WHERE RANK = 1
;
 	 
SELECT DEPARTMENT_NAME 
	 , JOB_TITLE
	 , AVG_SALARY
	 , RANK() OVER( ORDER BY AVG_SALARY ASC) AS RANK
  FROM (SELECT D.DEPARTMENT_NAME 
			 , J.JOB_TITLE 
	 		 , AVG(SALARY) AS AVG_SALARY
  		  FROM EMPLOYEES E
         INNER JOIN DEPARTMENTS D
            ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
         INNER JOIN JOBS J
            ON E.JOB_ID = J.JOB_ID
         GROUP BY D.DEPARTMENT_NAME 
 	         , J.JOB_TITLE )
 	 
 	 
SELECT D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , AVG(SALARY) AS AVG_SALARY
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
 GROUP BY D.DEPARTMENT_NAME 
 	 , J.JOB_TITLE  	 

/*
SELECT DEPARTMENT_NAME
 	 , JOB_TITLE
 	 , AVG(SALARY)
 	 , RANK() OVER( ORDER BY AVG(SALARY) ASC ) AS RANK
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
 WHERE RANK = 1
 GROUP BY DEPARTMENT_NAME
 	 , JOB_TITLE
; */

-- 118. 대륙명별 사원 수를 대륙명으로 오름차순 정렬하여 조회한다.
SELECT R.REGION_NAME
     , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON R.REGION_ID = C.REGION_ID 
 GROUP BY R.REGION_NAME 
 ORDER BY R.REGION_NAME ASC 
;
-- 119. 수행중인 직무의 최대급여(JOBS.MAX_SALARY)보다 더 많은 급여를 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.SALARY > (SELECT J.MAX_SALARY
 					 FROM JOBS J
 					WHERE J.JOB_ID = E.JOB_ID)
;

-- 120. 입사연도별 최소급여를 조회한다.
SELECT MIN(SALARY)
     , HIRE_YEAR
  FROM (SELECT SALARY
             , TO_CHAR(HIRE_DATE, 'YYYY') AS  HIRE_YEAR
          FROM EMPLOYEES)
 GROUP BY HIRE_YEAR
 ORDER BY HIRE_YEAR ASC
;
-- 121. 사원 이름의 글자수 별 사원의 수를 조회한다.

SELECT FIRST_NAME_LENGTH
     , COUNT(EMPLOYEE_ID)
  FROM (SELECT LENGTH(FIRST_NAME) AS FIRST_NAME_LENGTH
             , EMPLOYEE_ID
          FROM EMPLOYEES)
 GROUP BY FIRST_NAME_LENGTH
 ORDER BY
;
-- 122. 사원 성의 글자수 별 사원의 수를 조회한다.

-- 123. 커미션을 포함한 급여가 10000 이상인 사원의 모든 정보를 조회한다.
SELECT *
  FROM EMPLOYEES
 WHERE SALARY >= 10000
;

SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE COMMISSION_PCT * SALARY + SALARY >= 10000
;

SELECT EMPLOYEE_ID
	  ,FIRST_NAME 
	  ,LAST_NAME 
	  ,EMAIL
	  ,PHONE_NUMBER 
	  ,HIRE_DATE
	  ,JOB_ID
	  ,SALARY
	  ,COMMISSION_PCT
	  ,MANAGER_ID
	  ,DEPARTMENT_ID
  FROM (SELECT EMPLOYEE_ID
	  		 , FIRST_NAME 
	         , LAST_NAME 
	 		 , EMAIL
	 		 , PHONE_NUMBER 
	 		 , HIRE_DATE
	 		 , JOB_ID
	 		 , SALARY
	 		 , COMMISSION_PCT
	 		 , MANAGER_ID
	 		 , DEPARTMENT_ID
	 		 , (NVL(COMMISSION_PCT, 0)* SALARY) + SALARY AS TOTAL_SALARY
          FROM EMPLOYEES)
 WHERE TOTAL_SALARY >= 10000
;
-- 124. 국가 아이디의 첫 글자와 국가명의 첫 글자가 다른 모든 국가를 조회한다.
SELECT COUNTRY_ID
  FROM COUNTRIES
 WHERE SUBSTR(COUNTRY_ID, 1, 1) != SUBSTR(COUNTRY_NAME, 1, 1)
;

SELECT COUNTRY_ID
  FROM (SELECT COUNTRY_ID
  	         , SUBSTR(COUNTRY_ID, 1, 1) AS ID_FIRST_LETTER
  	         , SUBSTR(COUNTRY_NAME, 1, 1) AS NAME_FIRST_LETTER
  	      FROM COUNTRIES)
 WHERE ID_FIRST_LETTER != NAME_FIRST_LETTER 
;

-- 124-2 국가 아이디의 첫 글자와 국가명의 첫 글자가 같은 국가의 이름, 국가 아이디,
--       해당 국가의 부서 이름을 조회한다.
 SELECT C.COUNTRY_NAME
 	  , C.COUNTRY_ID 
 	  , D.DEPARTMENT_NAME 
   FROM (SELECT COUNTRY_NAME
     		  , COUNTRY_ID
  		   FROM COUNTRIES
 		  WHERE SUBSTR(COUNTRY_ID,1,1) = SUBSTR(COUNTRY_NAME,1,1)) C
  INNER JOIN LOCATIONS L
     ON C.COUNTRY_ID = L.COUNTRY_ID 
  INNER JOIN DEPARTMENTS D
     ON D.LOCATION_ID = L.LOCATION_ID 
;

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE SUBSTR(C.COUNTRY_ID,1,1) = SUBSTR(C.COUNTRY_NAME,1,1)
 
SELECT COUNTRY_NAME
     , COUNTRY_ID
  FROM COUNTRIES
 WHERE SUBSTR(C.COUNTRY_ID,1,1) = SUBSTR(C.COUNTRY_NAME,1,1)
 
-- 125. 이름의 첫 번째 글자별 평균급여를 조회한다.

SELECT AVG(SALARY)
	 , SUBSTR(FIRST_NAME, 1, 1)
  FROM EMPLOYEES
 GROUP BY SUBSTR(FIRST_NAME, 1, 1)
 ORDER BY SUBSTR(FIRST_NAME, 1, 1) ASC
;

SELECT NAME
  	 , AVG(SALARY)
  FROM (SELECT SALARY
  		     , SUBSTR(FIRST_NAME, 1, 1) AS NAME
  		  FROM EMPLOYEES)
 GROUP BY NAME
 ORDER BY NAME ASC
;
-- 126. 많은 급여를 받는 10명을 조회한다.
--ROWNUM
SELECT EMPLOYEE_ID
     , SALARY
     , ROWNUM
  FROM (SELECT EMPLOYEE_ID
		     , SALARY 
		  FROM EMPLOYEES
		 ORDER BY SALARY DESC )
 WHERE ROWNUM <= 10
;

SELECT EMPLOYEE_ID
     , SALARY 
  FROM EMPLOYEES
 ORDER BY SALARY DESC
;

--ROWNUMBER
SELECT EMPLOYEE_ID 
	 , SALARY
	 , RANK
  FROM (SELECT SALARY
  			 , EMPLOYEE_ID 
  			 , ROW_NUMBER() OVER( ORDER BY SALARY DESC ) AS RANK
  		  FROM EMPLOYEES)
 WHERE RANK <= 10
; 

SELECT SALARY
  FROM EMPLOYEES
 WHERE ROW_NUMBER() OVER( ORDER BY SALARY DESC ) AS RANK
; 
-- 127. 많은 급여를 받는 사원 중 11번 째 부터 20번째를 조회한다.
-- ROWNUM
SELECT EMPLOYEE_ID
	 , RNUM
	 , SALARY
  FROM (SELECT EMPLOYEE_ID
			 , ROWNUM AS RNUM
			 , SALARY
		  FROM (SELECT EMPLOYEE_ID
				     , SALARY
				  FROM EMPLOYEES
				 ORDER BY SALARY DESC)
		 WHERE ROWNUM <= 20)
 WHERE RNUM >= 11
;

SELECT EMPLOYEE_ID
	 , ROWNUM AS RNUM
  FROM (SELECT EMPLOYEE_ID
		     , SALARY
		  FROM EMPLOYEES
		 ORDER BY SALARY DESC)
 WHERE ROWNUM <= 20
;

SELECT EMPLOYEE_ID
     , SALARY
  FROM EMPLOYEES
 ORDER BY SALARY DESC 
;

-- ROW NUMBER
SELECT EMPLOYEE_ID 
	 , SALARY
	 , RANK
  FROM (SELECT SALARY
  			 , EMPLOYEE_ID 
  			 , ROW_NUMBER() OVER( ORDER BY SALARY DESC ) AS RANK
  		  FROM EMPLOYEES)
 WHERE RANK BETWEEN 11 AND 20
; 
-- 128. 가장 적은 급여를 받는 중 90번 째 부터 100번째를 조회한다.
SELECT EMPLOYEE_ID
	 , RNUM
	 , SALARY
  FROM (SELECT EMPLOYEE_ID
			 , ROWNUM AS RNUM
			 , SALARY
		  FROM (SELECT EMPLOYEE_ID
				     , SALARY
				  FROM EMPLOYEES
				 ORDER BY SALARY ASC)
		 WHERE ROWNUM <= 100)
 WHERE RNUM >= 90
;


-- ROWNUMBER
SELECT EMPLOYEE_ID 
	 , SALARY
	 , RANK
  FROM (SELECT SALARY
  			 , EMPLOYEE_ID 
  			 , ROW_NUMBER() OVER( ORDER BY SALARY DESC ) AS RANK
  		  FROM EMPLOYEES)
 WHERE RANK BETWEEN 90 AND 100
;
-- 129. 가장 적은 급여를 받는 사원의 상사명, 부서명을 조회한다.
SELECT E.MANAGER_ID 
     , D.DEPARTMENT_NAME
     , E.SALARY
     , E.FIRST_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 WHERE E.JOB_ID IN (SELECT JOB_ID
 					 FROM JOBS
 					WHERE E.SALARY = MIN_SALARY)
;

SELECT E_MAN.FIRST_NAME
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES E_MAN
    ON E.MANAGER_ID = E_MAN.EMPLOYEE_ID 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.SALARY = (SELECT MIN(SALARY)
 					 FROM EMPLOYEES)
;
-- 130. 'PU_CLERK' 직무인 2번째 부터 5번째 사원의 부서명, 직무명을 조회한다. PAGINATION
SELECT DEPARTMENT_NAME
     , JOB_TITLE
     , RNUM
  FROM (SELECT DEPARTMENT_NAME
		     , JOB_TITLE
		     , ROWNUM AS RNUM
		  FROM (SELECT DEPARTMENT_NAME
					 , JOB_TITLE
				  FROM EMPLOYEES E
				 INNER JOIN DEPARTMENTS D
				    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
				 INNER JOIN JOBS J
				    ON J.JOB_ID = E.JOB_ID
				 WHERE J.JOB_ID = 'PU_CLERK')
		 WHERE ROWNUM <= 5)
 WHERE RNUM >= 2
;

SELECT DEPARTMENT_NAME
     , JOB_TITLE
     , ROWNUM AS RNUM
  FROM (SELECT DEPARTMENT_NAME
			 , JOB_TITLE
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
		 INNER JOIN JOBS J
		    ON J.JOB_ID = E.JOB_ID
		 WHERE J.JOB_ID = 'PU_CLERK')
 WHERE ROWNUM <= 5
;

SELECT D.DEPARTMENT_NAME
	 , J.JOB_TITLE
	 , E.EMPLOYEE_ID
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
 WHERE J.JOB_ID = 'PU_CLERK'
;    
    
-- 131. 월별 최대급여 중 2번째 부터 4번째 데이터만 조회한다.
-- ROWNUM
SELECT MAX(SALARY) AS MAX_SAL
     , TO_CHAR(HIRE_DATE, 'MM') AS MM
  FROM EMPLOYEES
;

SELECT MAX_SAL
     , MM
     , ROWNUM AS RNUM
  FROM (SELECT MAX(SALARY) AS MAX_SAL
		     , TO_CHAR(HIRE_DATE, 'MM') AS MM
		  FROM EMPLOYEES
		 GROUP BY TO_CHAR(HIRE_DATE, 'MM'))
 WHERE ROWNUM <= 4
;

SELECT MAX_SAL
     , MM
     , RNUM 
  FROM (SELECT MAX_SAL
		     , MM
		     , ROWNUM AS RNUM
		  FROM (SELECT MAX(SALARY) AS MAX_SAL
				     , TO_CHAR(HIRE_DATE, 'MM') AS MM
				  FROM EMPLOYEES
				 GROUP BY TO_CHAR(HIRE_DATE, 'MM'))
		 WHERE ROWNUM <= 4) 
 WHERE RNUM >= 2
;

-- ROW NUMBER
SELECT RANK
	 , MAX_SAL
	 , MM
  FROM (SELECT TO_CHAR(HIRE_DATE, 'MM') AS MM
	 		 , MAX(SALARY) AS MAX_SAL
	 		 , ROW_NUMBER() OVER( ORDER BY MAX(SALARY) DESC ) AS RANK
  		  FROM EMPLOYEES
  		 GROUP BY TO_CHAR(HIRE_DATE, 'MM'))
 WHERE RANK BETWEEN 2 AND 4
;

SELECT TO_CHAR(HIRE_DATE, 'MM')
	 , MAX(SALARY)
	 , ROW_NUMBER() OVER( ORDER BY MAX(SALARY) DESC ) AS RANK
  FROM EMPLOYEES
;
-- 132. 근무중인 사원이 가장 많은 도시와 사원의 수를 조회한다. 
-- ROWNUM

SELECT CITY
     , EMP_CNT
     , ROWNUM
  FROM (SELECT CITY
		     , COUNT(EMPLOYEE_ID) AS EMP_CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
		 INNER JOIN LOCATIONS L
		    ON L.LOCATION_ID = D.LOCATION_ID
		 GROUP BY CITY
		 ORDER BY EMP_CNT DESC)
 WHERE ROWNUM = 1
;

SELECT CITY
     , COUNT(EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
 GROUP BY CITY
 ORDER BY EMP_CNT DESC
;  


-- ROWNUMBER
 SELECT CITY
 	  , ID_CNT
      , RANK
   FROM (SELECT DEPARTMENT_ID 
   			  , COUNT(EMPLOYEE_ID) AS ID_CNT
	 		  , RANK() OVER( ORDER BY ID_CNT DESC ) AS RANK
  		   FROM EMPLOYEES) E
  INNER JOIN DEPARTMENTS D
     ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
  INNER JOIN LOCATIONS L
     ON L.LOCATION_ID = D.DEPARTMENT_ID
  WHERE RANK = 1
;

(SELECT COUNT(EMPLOYEE_ID) AS ID_CNT
	 , RANK() OVER( ORDER BY EMPLOYEE_ID DESC ) AS RANK
  FROM EMPLOYEES) E	 
;
-- 133. 사원의 수가 가장 많은 부서명, 사원의 수를 조회한다.
-- ROWNUM
SELECT DEPARTMENT_NAME
     , EMP_CNT
     , ROWNUM
  FROM (SELECT DEPARTMENT_NAME
		     , COUNT(EMPLOYEE_ID) AS EMP_CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
		 GROUP BY DEPARTMENT_NAME
		 ORDER BY EMP_CNT DESC)
 WHERE ROWNUM = 1
;

		 
SELECT DEPARTMENT_NAME
     , COUNT(EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 GROUP BY DEPARTMENT_NAME
 ORDER BY EMP_CNT DESC
;


-- ROWNUMBER
SELECT D.DEPARTMENT_NAME 
     , ID_CNT
  FROM (SELECT DEPARTMENT_ID
  			 , EMPLOYEE_ID
  		  FROM (SELECT DEPARTMENT_ID
  					 , EMPLOYEE_ID
  		  			 , ROW_NUMBER() OVER( ORDER BY ID_CNT DESC) AS RANK
 				  FROM (SELECT DEPARTMENT_ID
  					 		 , EMPLOYEE_ID
  		  					 , COUNT(EMPLOYEE_ID) AS ID_CNT
 				  		  FROM EMPLOYEES
 				  		 GROUP BY DEPARTMENT_ID) ) ) E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID	
; 

(SELECT COUNT(EMPLOYEE_ID)
	 , ROW_NUMBER() OVER( ORDER BY COUNT(EMPLOYEE_ID) DESC) AS RANK
  FROM EMPLOYEES) E
;

SELECT COUNT(EMPLOYEE_ID) AS ID_CNT
  FROM EMPLOYEES
 
-- 134. 가장 많은 부서가 있는 도시를 조회한다. 도시별 부서의 수
SELECT CITY
     , DEP_CNT
     , ROWNUM
  FROM (SELECT CITY
		     , COUNT(DEPARTMENT_ID) AS DEP_CNT
		  FROM DEPARTMENTS D
		 INNER JOIN LOCATIONS L
		    ON L.LOCATION_ID = D.LOCATION_ID
		 GROUP BY CITY
		 ORDER BY DEP_CNT DESC)
 WHERE ROWNUM = 1
;
  
SELECT CITY
     , COUNT(DEPARTMENT_ID) AS DEP_CNT
  FROM DEPARTMENTS D
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
 GROUP BY CITY
 ORDER BY DEP_CNT DESC
;
-- 강사님
SELECT RANK
	 , CITY
	 , DEPT_CNT
  FROM (SELECT CITY
			 , DEPT_CNT
			 , RANK() OVER( ORDER BY DEPT_CNT DESC ) AS RANK
		  FROM (SELECT L.CITY
					 , COUNT(D.DEPARTMENT_ID) AS DEPT_CNT
				  FROM DEPARTMENTS D
				 INNER JOIN LOCATIONS L
				    ON D.LOCATION_ID = L.LOCATION_ID
				 GROUP BY L.CITY))
 WHERE RANK = 1
;

-- ROWNUM
SELECT CITY
	 , DEPT_CNT
  FROM (SELECT L.CITY
			 , COUNT(D.DEPARTMENT_ID) AS DEPT_CNT
		  FROM DEPARTMENTS D
		 INNER JOIN LOCATIONS L
		    ON D.LOCATION_ID = L.LOCATION_ID
		 GROUP BY L.CITY
		 ORDER BY DEPT_CNT DESC)
 WHERE ROWNUM = 1
;


  
-- 135. 가장 많은 사원이 있는 부서의 국가명을 조회한다. 부서별 사원의 수 
-- ROWNUM
SELECT COUNTRY_NAME
     , EMP_CNT
     , ROWNUM
  FROM (SELECT COUNTRY_NAME
		     , COUNT(EMPLOYEE_ID) AS EMP_CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
		 INNER JOIN LOCATIONS L
		    ON L.LOCATION_ID = D.LOCATION_ID 
		 INNER JOIN COUNTRIES C
		    ON C.COUNTRY_ID = L.COUNTRY_ID 
		 GROUP BY C.COUNTRY_NAME 
		 ORDER BY EMP_CNT DESC)
 WHERE ROWNUM = 1
;

SELECT COUNTRY_NAME
     , COUNT(EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID 
 GROUP BY C.COUNTRY_NAME 
 ORDER BY EMP_CNT DESC
;


-- RANK OVER
SELECT COUNTRY_NAME
  FROM COUNTRIES
 WHERE COUNTRY_ID = (SELECT COUNTRY_ID
					   FROM LOCATIONS
					  WHERE LOCATION_ID = (SELECT LOCATION_ID
										     FROM DEPARTMENTS
										    WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
																     FROM (SELECT DEPARTMENT_ID
																			    , EMP_CNT
																			    , RANK() OVER ( ORDER BY EMP_CNT DESC ) AS RANK
																		     FROM (SELECT DEPARTMENT_ID
																					    , COUNT(EMPLOYEE_ID) AS EMP_CNT
																				     FROM EMPLOYEES 
																				    GROUP BY DEPARTMENT_ID))
																    WHERE RANK = 1)))
;
-- 어떤 부서의 국가 번호와 같은 것
SELECT COUNTRY_ID
  FROM LOCATIONS
 WHERE LOCATION_ID = (SELECT LOCATION_ID
					    FROM DEPARTMENTS
					   WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
											    FROM (SELECT DEPARTMENT_ID
														   , EMP_CNT
														   , RANK() OVER ( ORDER BY EMP_CNT DESC ) AS RANK
													    FROM (SELECT DEPARTMENT_ID
																   , COUNT(EMPLOYEE_ID) AS EMP_CNT
															    FROM EMPLOYEES 
															   GROUP BY DEPARTMENT_ID))
											   WHERE RANK = 1))
;
-- 어떤 부서의 지역 번호와 같은 것
SELECT LOCATION_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
						  FROM (SELECT DEPARTMENT_ID
									 , EMP_CNT
									 , RANK() OVER ( ORDER BY EMP_CNT DESC ) AS RANK
								  FROM (SELECT DEPARTMENT_ID
											 , COUNT(EMPLOYEE_ID) AS EMP_CNT
										  FROM EMPLOYEES 
										 GROUP BY DEPARTMENT_ID))
						 WHERE RANK = 1)
;

-- ROWNUM
SELECT COUNTRY_NAME
  FROM COUNTRIES
 WHERE COUNTRY_ID = (SELECT COUNTRY_ID
					   FROM LOCATIONS
					  WHERE LOCATION_ID = (SELECT LOCATION_ID
										     FROM DEPARTMENTS
										    WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
																     FROM (SELECT DEPARTMENT_ID
																			    , COUNT(EMPLOYEE_ID) AS EMP_CNT
																		     FROM EMPLOYEES 
																		    GROUP BY DEPARTMENT_ID
																		    ORDER BY EMP_CNT DESC)
																    WHERE ROWNUM = 1)))
;


-- 136. 'Europe' 에서 가장 많은 사원들이 있는 부서명을 조회한다.  유럽에서 근무하고 있는 사원들의 부서별 사원 수 > 가장 많은 사원 수 1번 구함 

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE LOCATION_ID = (SELECT LOCATION_ID
 						FROM LOCATIONS
 					   WHERE COUNTRY_ID = (SELECT COUNTRY_ID
 					   						 FROM COUNTRIES
 					   						WHERE REGION_ID = (SELECT REGION_ID
 					   						                     FROM REGIONS
 					   						                    WHERE REGION NAME = 'Europe')))

SELECT DEPARTMENT_NAME
     , EMP_CNT
     , ROWNUM
  FROM (SELECT DEPARTMENT_NAME
		     , COUNT(EMPLOYEE_ID) AS EMP_CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
		 INNER JOIN LOCATIONS L
		    ON L.LOCATION_ID = D.LOCATION_ID 
		 INNER JOIN COUNTRIES C
		    ON C.COUNTRY_ID = L.COUNTRY_ID
		 INNER JOIN REGIONS R
		    ON R.REGION_ID = C.REGION_ID
		 WHERE R.REGION_NAME = 'Europe'
		 GROUP BY D.DEPARTMENT_NAME
		 ORDER BY EMP_CNT DESC)
 WHERE ROWNUM = 1
;

SELECT DEPARTMENT_NAME
     , COUNT(EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID
 INNER JOIN REGIONS R
    ON R.REGION_ID = C.REGION_ID 
 GROUP BY D.DEPARTMENT_NAME
 ORDER BY EMP_CNT DESC
;


-- 137. 100번 사원의 모든 부하직원을 계층조회한다. 단, LEVEL이 4인 사원은 제외한다.
 SELECT EMPLOYEE_ID
	  , FIRST_NAME 
	  , LAST_NAME 
	  , EMAIL
	  , PHONE_NUMBER 
	  , HIRE_DATE
	  , JOB_ID
	  , SALARY
	  , COMMISSION_PCT
	  , MANAGER_ID
	  , DEPARTMENT_ID
 	  , LEVEL
   FROM EMPLOYEES
  WHERE LEVEL != 4
  START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID 
;
-- 138. 101번 사원의 모든 부하직원 들의 이름, 성, 상사사원번호, 상사사원명을 계층 조회한다.
 SELECT FIRST_NAME 
	  , LAST_NAME 
	  , MANAGER_ID
	  , LEVEL
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = 101
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID  -- PK가 FK 로 흘러가는 방향 : 정방향 
;
-- 139. 114번 직원의 모든 상사들의 이름, 성, 상사사원번호, 상사사원명을 계층 조회한다.
 SELECT FIRST_NAME 
	  , LAST_NAME 
	  , MANAGER_ID
	  , LEVEL
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = 114
CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID  -- 부하가 아닌 상사 조회 부하직원에서 > 상사 FK > PK 역방향
;

-- 140. 114번 직원의 모든 상사들의 이름, 성, 상사사원번호, 상사사원명을 역순으로 계층 조회한다.
 SELECT FIRST_NAME 
	  , LAST_NAME 
	  , MANAGER_ID
	  , LEVEL
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = 114
CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID
  ORDER BY LEVEL DESC
;

-- 141. 부서별 사원의 수를 조인을 이용해 다음과 같이 조회한다."부서명 (사원의 수)"
SELECT DEPARTMENT_NAME || ' ('|| COUNT(EMPLOYEE_ID) ||')'
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
;
-- 142. 부서별 사원의 수를 스칼라쿼리를 이용해 다음과 같이 조회한다. "부서명 (사원의 수)"
SELECT (SELECT D.DEPARTMENT_NAME
		  FROM DEPARTMENTS D
		 WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) || ' ('|| (SELECT COUNT(EMPLOYEE_ID)
  															   FROM EMPLOYEES) ||')'
  FROM EMPLOYEES E
;

-- 143. 사원의 정보를 다음과 같이 조회한다. "사원번호 번 사원의 이름은 성이름 입니다."
SELECT EMPLOYEE_ID || '번 사원의 이름은 ' || LAST_NAME || FIRST_NAME || '입니다.'
  FROM EMPLOYEES
;

-- 144. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. 
--      "사원번호 번 사원의 상사명은 상사명 입니다."
  
SELECT E.EMPLOYEE_ID || '번 사원의 상사명은' || (SELECT EM.FIRST_NAME
		    								   FROM EMPLOYEES EM
											  WHERE EM.EMPLOYEE_ID = E.MANAGER_ID) || '입니다.'
  FROM EMPLOYEES E
;  

-- 145. 사원의 정보를 조인을 이용해 다음고 같이 조회한다. "사원명 (직무명)"
SELECT E.FIRST_NAME ||' ('|| JOB_TITLE ||')'
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
;

-- 146. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원명 (직무명)"
SELECT E.FIRST_NAME ||' ('|| (SELECT J.JOB_TITLE
  							    FROM JOBS J
 							   WHERE J.JOB_ID = E.JOB_ID) ||')'
  FROM EMPLOYEES E
;


-- 147. 부서별 급여 차이(최고급여 - 최저급여)가 가장 큰 부서명을 조회한다. 부서명별 최고급여- 최저급여 > 가장 큰곳 찾기 
SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
-- 148. 부서별 급여 차이(최고급여 - 최저급여)가 가장 큰 부서에서 근무하는 사원들의 직무명을 
--      중복없이 조회한다.

-- 149. 부하직원이 없는 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.SALARY
	 , E.JOB_ID
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID 
  FROM EMPLOYEES E 
 WHERE E.EMPLOYEE_ID NOT IN (SELECT MANAGER_ID
 							   FROM EMPLOYEES
 							  WHERE MANAGER_ID IS NOT NULL )
  -- 내 사원번호가 없다 다른사람들의 상사번호에 
;
-- 150. 사원번호가 100번인 사원의 사원번호, 이름과 
--      사원번호로 내림차순 정렬된 사원의 사원번호, 이름을 조회한다.
/*조회 예
--------------------
100    Steven
206    William
205    Shelley
204    Hermann
203    Susan
202    Pat
201    Michael
200    Jennifer
199    Douglas
198    Donald
197    Kevin
196    Alana
...
*/

-- 151. 모든 사원들의 이름과 부서번호, 부서명을 조회한다. 근무중인 부서가 없는 경우도 조회한다.
SELECT E.FIRST_NAME
     , D.DEPARTMENT_ID
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
;

-- 152. 모든 사원들의 이름과 부서번호, 부서명, 근무중인 도시를 조회한다. 근무중인 부서가 없거나 근무중인 도시가 없는 경우도 조회한다.
SELECT E.FIRST_NAME
     , D.DEPARTMENT_ID
     , D.DEPARTMENT_NAME
     , L.CITY
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
  LEFT OUTER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
;
  

-- 153. 부서별로 근무중인 사원의 수를 조회한다. 근무중인 사원이 없는 부서는 0으로 조회한다.
SELECT D.DEPARTMENT_NAME
	 , NVL(COUNT(E.EMPLOYEE_ID), 0)
  FROM DEPARTMENTS D
  LEFT OUTER JOIN EMPLOYEES E
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME 
;

-- 154. 도시별로 존재하는 부서의 수를 조회한다. 존재하는 부서가 없는 도시는 0으로 조회한다.
SELECT L.CITY
     , NVL(COUNT(D.DEPARTMENT_ID), 0)
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D
    ON D.LOCATION_ID = L.LOCATION_ID 
 GROUP BY L.CITY
;

-- 155. 도시별로 근무중인 사원의 수를 조회한다. 근무중인 사원이 없는 도시는 0으로 조회한다.
SELECT L.CITY
	 , NVL(COUNT(EMPLOYEE_ID), 0)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 RIGHT OUTER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 GROUP BY L.CITY
;

-- 156. 모든 사원의 정보와 직무 변경이력을 함께 조회한다. 직무변경이력이 없는 사원도 함께 조회한다.
SELECT JH.JOB_ID
     , E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.SALARY
	 , E.JOB_ID
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOB_HISTORY JH 
    ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
;

-- 157. 모든 사원의 현재 수행중인 직무명, 현재 근무중인 부서명, 이전에 수행한 직무명, 이전에 근무한 부서명을 조회한다.
--     과거 직무와 이전 부서명이 없는 사원도 함께 조회한다.

SELECT J.JOB_TITLE
	 , D.DEPARTMENT_NAME
	 , JH
  FROM
  
  
  
  
